#ifdef RTK_1319_PLATFORM
#undef CONFIG_DYNAMIC_RX_BUF
#endif

#ifdef RTK_1619B_PLATFORM
#undef CONFIG_DYNAMIC_RX_BUF
#endif

#ifdef CONFIG_PLATFORM_AML_S905
#undef CONFIG_DYNAMIC_RX_BUF
#endif

#ifdef CONFIG_PLATFORM_HUANGLONG
#undef CONFIG_DYNAMIC_RX_BUF
#endif
